### ISSUE TITLE
Game Pass for PC support

### ISSUE THREAD

**Issue by kwonyoong** [XeonKHJ/GamePassScores#1]
Thanks for the app.
I'm PC gamer.
I hope that this app support the list of Game Pass for PC.
If this app support PC, maybe it needs filtering option. (XBOX / PC)
Anyway, Thanks for this excellent app!
Have a good day :)

**Comment by XeonKHJ** [comment]
I plan to bring that feature to the app soon. Right now there is a website called [Gamepassta](https://www.gamepassta.com/)that meets your needs.

**Comment by XeonKHJ** [comment]
PC games support is out now.
https://github.com/XeonKHJ/GamePassScores/commit/ce0d9bba4f1fdce5b3d633d70678a289e0374100
