### ISSUE TITLE
Leaving soon option doesn't seem to work.

### ISSUE THREAD

**Issue by alexsuncn** [XeonKHJ/GamePassScores#3]
When choose "Leaving soon", I got empty result. Howerver, "Recently added" works fine.

**Comment by XeonKHJ** [comment]
Yes. I notice the issue as well. I'll fix it once I have time. (way too busy these days). Thanks for issuing this bug.

**Comment by XeonKHJ** [comment]
Fixed. My server was unable to fetch the game info correctly. It's now fixed. Refresh and you'sll see the Leaving Soon list.
