### ISSUE TITLE
Pulling incorrect meta scores for some games

### ISSUE THREAD

**Issue by Denholm** [XeonKHJ/GamePassScores#4]
Some of the scores shown in game are incorrect. 

Example:
In app Darkest Dungeon has a 53%
But, if you look at Metacritic it shows a 84%

Where is this data coming from, is it being calculated incorrectly?

**Comment by XeonKHJ** [comment]
I just checked that Darkest Dungeon has left XGP. 
I might be  making a mistake when I manuly change a metacritic path for a game profile (Confused it with DARK ALLIANCE). Thanks for noticing.  
Some games' title dosn't align with Metacritic so I have to update it manually. It could be a mistake.
